# Generated by Django 4.1.7 on 2023-05-29 13:39

import App.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='username',
            field=App.models.EncryptedField(max_length=255),
        ),
    ]
