# Generated by Django 4.1.7 on 2023-04-01 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposit',
            name='first_name',
            field=models.CharField(default=0, max_length=150),
            preserve_default=False,
        ),
    ]
