# Generated by Django 4.1.7 on 2023-06-20 20:07

import App.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_alter_useraccount_account_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='account_number',
            field=App.models.EncryptedField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='username',
            field=App.models.EncryptedField(max_length=255),
        ),
    ]
