# Generated by Django 4.1.7 on 2023-05-29 13:51

import App.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_alter_useraccount_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit',
            name='username',
            field=App.models.EncryptedField(max_length=255),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='sender_username',
            field=App.models.EncryptedField(max_length=255),
        ),
        migrations.AlterField(
            model_name='withdraw',
            name='username',
            field=App.models.EncryptedField(max_length=255),
        ),
    ]
