# Generated by Django 4.1.7 on 2023-04-01 14:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('App', '0003_remove_deposit_first_name_deposit_user_first_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deposit',
            name='user_first_name',
        ),
        migrations.AddField(
            model_name='deposit',
            name='user',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
