# Generated by Django 4.1.7 on 2023-04-01 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_deposit_user_first_name_deposit_user_last_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deposit',
            old_name='user_username',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='deposit',
            old_name='user_first_name',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='deposit',
            name='user_last_name',
        ),
        migrations.AddField(
            model_name='deposit',
            name='first_name',
            field=models.CharField(default='192', max_length=30),
            preserve_default=False,
        ),
    ]
