# Generated by Django 4.1.7 on 2023-04-02 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0008_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
