# Generated by Django 4.1.7 on 2023-04-02 18:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('App', '0010_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='first_name',
            field=models.CharField(default='192', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='last_name',
            field=models.CharField(default='moyo', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='user',
            field=models.ForeignKey(default=12, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='username',
            field=models.CharField(default='1902021', max_length=30),
            preserve_default=False,
        ),
    ]
