# Generated by Django 4.1.7 on 2023-04-02 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0012_useraccountnumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccountnumber',
            name='username',
            field=models.CharField(default='hello', max_length=30),
            preserve_default=False,
        ),
    ]
