# Generated by Django 4.1.7 on 2023-04-02 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0013_useraccountnumber_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccountnumber',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='useraccountnumber',
            name='last_name',
        ),
    ]
