# Generated by Django 4.1.7 on 2023-04-05 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0014_remove_useraccountnumber_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='last_name',
        ),
    ]
