# Generated by Django 4.1.7 on 2023-04-05 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0015_remove_transaction_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccountnumber',
            name='balance',
            field=models.FloatField(default=0),
        ),
    ]
