# Generated by Django 4.1.7 on 2023-04-05 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0018_alter_transaction_recipient_account_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deposit',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='deposit',
            name='last_name',
        ),
    ]
