# Generated by Django 4.1.7 on 2023-04-05 22:47

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('App', '0019_remove_deposit_first_name_remove_deposit_last_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserAccountNumber',
            new_name='UserAccount',
        ),
    ]
