# Generated by Django 4.1.7 on 2023-04-06 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0021_rename_transaction_transfer_withdraw'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transfer',
            old_name='timestamp',
            new_name='date',
        ),
    ]
