# Generated by Django 4.1.7 on 2023-04-06 21:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0022_rename_timestamp_transfer_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraccount',
            old_name='accountBalance',
            new_name='account_balance',
        ),
        migrations.AlterField(
            model_name='transfer',
            name='recipient_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_transaction', to='App.useraccount'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='sender_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_transaction', to='App.useraccount'),
        ),
    ]
