# Generated by Django 4.1.7 on 2023-04-07 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0025_alter_useraccount_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transfer',
            old_name='transfer_amount',
            new_name='amount',
        ),
    ]
