# Generated by Django 4.1.7 on 2023-04-07 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0026_rename_transfer_amount_transfer_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='account_balance',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
