# Generated by Django 4.1.7 on 2023-04-07 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0027_alter_useraccount_account_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='account_balance',
            field=models.FloatField(default=0),
        ),
    ]
