# Generated by Django 4.1.7 on 2023-04-07 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0028_alter_useraccount_account_balance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transfer',
            old_name='username',
            new_name='receiver_username',
        ),
        migrations.AddField(
            model_name='transfer',
            name='sender_username',
            field=models.CharField(default='test', max_length=30),
            preserve_default=False,
        ),
    ]
