# Generated by Django 4.1.7 on 2023-04-07 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0029_rename_username_transfer_receiver_username_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transfer',
            name='sender_username',
        ),
    ]
