# Generated by Django 4.1.7 on 2023-04-11 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0030_remove_transfer_sender_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transfer',
            old_name='receiver_username',
            new_name='sender_username',
        ),
    ]
